---
exclude: (?x)^( \.idea/.* |.*cache/.* |.scannerwork/.* |.*properties )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      # - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: ^(tests/Json/Error/errorContrat.json)$
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      # - id: check-toml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--no-warnings, -d, '{extends: relaxed, rules: {line-length: {max: 120}}}']
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - -l 88
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, 'B101,B105,B110,B307,B310,B311', --recursive, .]
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
        args:
          - -i
          - -r
          - --expand-star-imports
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - pyproject-flake8==0.0.1a2
          - flake8-bugbear==22.1.11
          - flake8-comprehensions==3.8.0
          - flake8-2020==1.6.1
          - mccabe==0.6.1
          - pycodestyle==2.8.0
          - pyflakes==2.4.0
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [-l, '88', --profile, black]
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  #       args:
  #         - --ignore-words-list=hass
  #         - --skip="./.*"
  #         - --quiet-level=2
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --install-types, --non-interactive, --check-untyped-defs,
          --show-error-codes]
        additional_dependencies:
          - requests==2.23.0
  # TODO:  mdformat --wrap 75 README.md --number
