---
name: CI

on:
  push:
  schedule:
    - cron: 10 5 * * *

jobs:
  build:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [3.x, '3.7', '3.10', pypy-3.7, pypy-3.9]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: pytest tests/test_myEnedis.py
